---
- hosts: all
  gather_facts: false
  tasks:
    - name: Install dockcer
      package:
        name: docker
        state: present
    - name: enabale docker service
      service:
        name: docker
        state: started
        enabled: yes
    - name: disable the firewalld service
      service:
        name: firewalld
        state: stopped
        enabled: no
    - name: swarm leave
      shell: |
        docker swarm leave --force >/dev/null 2>&1 | true

- hosts: master
#  gather_facts: false
  tasks:
    - name: Initialize docker swarm
      shell: docker swarm init --advertise-addr "{{ ansible_default_ipv4.address }}"
    - name: get join command
      shell: docker swarm join-token manager | sed 1d | sed 1d | sed 4d | sed 's/\\//g' | tr '\n' ' '
      register: worker_join_command
    - name: run join command on workers
      set_fact:
        worker_join_command: "{{ worker_join_command.stdout_lines[0] }}"

- hosts: workers
  gather_facts: false
  tasks:
    - name: join swarm cluster
      shell: "{{ hostvars['master'].worker_join_command }} > /tmp/worker_joined.txt"

